### ISSUE TITLE
应用需求：识别传递的参数中 `{}` 的数量

### ISSUE THREAD

**Issue by xkwxdyy** [Sophanatprime/lt3ekeys#1]
## 需求描述
```latex
\cs_new_protected:Npn \__whu_define_constant:nn #1#2
  { \tl_const:cn { c__whu_constant_ #1 _tl } {#2} }
\cs_new_protected:Npn \__whu_define_constant:nnn #1#2#3
  {
    \tl_const:cn { c__whu_constant_ #1    _tl } {#2}
    \tl_const:cn { c__whu_constant_ #1 _en_tl } {#3}
  }

\NewDocumentCommand { \whudefineconstant } { s m }
  {
    \bool_if:nTF { #1 }
      {
        % \whudefineconstant { {<name>} {<content>} {<content_en>} list }
        \clist_map_inline:nn
          {
            #2
          }
          { \__whu_define_constant:nnn ##1 }
      }
      {
        % \whudefineconstant { {<name>} {<content>} list }
        \clist_map_inline:nn
          {
            #2
          }
          { \__whu_define_constant:nn ##1 }
      }
  }
```

上面定义了一个函数 `\whudefineconstant`，作用是批量定义一些常值的 `tl`，其中 `\whudefineconstant*` 还定义了英文的版本。

使用场景为论文模板开发中，定义一些固定的值比如“摘要”，“ABSTRACT”，“致谢”等。

但是有一个需求是需要额外定义这个常值的 `toc` 版本：具体来说，就是在设置一些章节标题的时候，比如“致谢”，可能样式是`致 \quad 谢`，但是在目录中仍然是 `致谢`。思路是定义两个 `tl`，`\c__whu_constant_acknowledgement_tl` 和 `\c__whu_constant_acknowledgement_toc_tl` 分别储存 `致 \quad 谢` 和 `致谢`，然后通过`\chapter[\c__whu_constant_acknowledgement_toc_tl]{\c__whu_constant_acknowledgement_tl}` 的方式来实现效果。

所以就想能把 `\whudefineconstant` 继续优化，甚至不需要带*版本。

## 功能设想
`\whudefineconstant` 依旧支持批量生成，即必选参数是一个 `clist`，其中每一个 item 是 2-5 个 `{}` 的组合，比如
```latex
\whudefineconstant{
  {acknowledgement}{致\quad谢}{ACKNOWLEDGEMENT}{致谢}{Acknowledgement},
  {abstract}{摘\qquad要}{Abstract}{摘要}
}
```
就定义了
- `\c__whu_constant_acknowledgement_tl`: `致\quad谢`
- `\c__whu_constant_acknowledgement_en_tl`: `ACKNOWLEDGEMENT`
- `\c__whu_constant_acknowledgement_toc_tl`: `致谢`
- `\c__whu_constant_acknowledgement_en_toc_tl`: `Acknowledgement`
和
- `\c__whu_constant_abstract_tl`: `摘\qquad要`
- `\c__whu_constant_abstract_en_tl`: `Abstract`
- `\c__whu_constant_abstract_toc_tl`: `摘要`
- `\c__whu_constant_abstract_en_toc_tl`: 缺省则表示和`\c__whu_constant_abstract_en_tl`相同，为`摘要`

总结来说就是
- `{}{name_zh}` 定义了中文的 tl，中文 toc tl 和中文 tl 相同
- `{}{name_zh}{name_en}` 定义了中文和英文的 tl，中英文的 toc 和对应 tl 相同
- `{}{name_zh}{name_en}{name_zh_toc}` 定义了中文和英文的 tl 以及中文的 toc，而英文的 toc tl 和英文 tl 相同
- `{}{name_zh}{name_en}{name_zh_toc}{name_en_toc}` 定义了中文和英文的 tl，以及中英文的 toc tl

所以识别每个 item 有多少个 `{}` 就是关键。

还考虑到如果某一个 `{}` 里仍然有 `{}`，比如 `{{\kaishu 摘}要}` （虽然可能不太常见），也需要能正确识别数量，可能需要 peek 配对的括号。

上述需求超出了我的能力范围，但是了解到 `lt3ekeys` 项目的定义命令自由度很高，看了一下手册，但门槛有点高，没咋看懂，就来请教一下，不知道这个需求 `lt3ekeys` 能否实现

**Comment by Sophanatprime** [comment]
用 `\tl_count:n` 计算一下每一项的长度，然后 `\int_case:nn` 根据长度分别处理即可。

像 `ltcmd`、`lt3ekeyscmd`，只是用于控制“如何获取参数”，比如获取花括号包裹的参数，获取方括号包裹的参数等等，而不关心如何处理参数。所以 `lt3ekeyscmd` 在这里用处不大。

**Comment by xkwxdyy** [comment]
了解了，感谢
